name: Daily Commit

on:
  schedule:
    - cron: '30 4 * * *'  # runs daily at 04:30 UTC (10:00 AM IST)
  workflow_dispatch:        # allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a dummy change
        run: |
          echo "Commit made on $(date)" >> daily_commit.log

      - name: Commit and push (by 23f3001973@ds.study.iitm.ac.in)
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email '23f3001973@ds.study.iitm.ac.in'
          git add daily_commit.log
          git commit -m "Daily commit on $(date)" || echo "Nothing to commit"
          git push
