name: Daily Commit

on:
  schedule:
    - cron: '30 4 * * *'  # Runs daily at 04:30 UTC (10:00 AM IST)
  workflow_dispatch:        # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a dummy change
        run: |
          echo "Commit made on $(date)" >> daily_commit.log

      - name: Commit and push (by 23f3001973@ds.study.iitm.ac.in)
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "23f3001973@ds.study.iitm.ac.in"
          git add daily_commit.log
          git commit -m "Daily commit on $(date)" || exit 0
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
